{
 "title": "Batteries",
 "description": "JKBMS MQTT Dashboard",
 "tags": [
  "battery",
  "JKBMS"
 ],
 "time": { "from": "now-3d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Current",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "b1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery",
     "query": "SELECT mean(\"Ain\") - mean(\"Aout\") FROM \"battery\" WHERE (\"topic\" = 'battery/JKBMS1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Ain" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "Aout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "battery/JKBMS1" }
     ]
    },
    {
     "alias": "b2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery",
     "query": "SELECT mean(\"Ain\") - mean(\"Aout\") FROM \"battery\" WHERE (\"topic\" = 'battery/JKBMS2') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Aout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "battery/JKBMS2" }
     ]
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "b1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "topic" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery",
     "query": "from(bucket: \"local-influxdb\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"battery-system\" and\r\n    r._field == \"current\"\r\n  )",
     "select": [
      [
       { "params": [ "V" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "battery/JKBMS1" }
     ]
    },
    {
     "alias": "b2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "topic" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery",
     "query": "from(bucket: \"local-influxdb\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"battery-system\" and\r\n    r._field == \"current\"\r\n  )",
     "select": [
      [
       { "params": [ "V" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "battery/JKBMS2" }
     ]
    }
   ]
  },
  {
   "title": "cell V delta",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "b1",
     "groupBy": [
      { "params": [ "topic" ], "type": "tag" }
     ],
     "measurement": "battery",
     "query": "from(bucket: \"local-influxdb\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"battery-system\" and\r\n    r._field == \"current\"\r\n  )",
     "select": [
      [
       { "params": [ "V_delta" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "battery/JKBMS1" }
     ]
    },
    {
     "alias": "b2",
     "groupBy": [
      { "params": [ "topic" ], "type": "tag" }
     ],
     "measurement": "battery",
     "query": "from(bucket: \"local-influxdb\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"battery-system\" and\r\n    r._field == \"current\"\r\n  )",
     "select": [
      [
       { "params": [ "V_delta" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "battery/JKBMS2" }
     ]
    }
   ]
  },
  {
   "title": "Remaining Capacity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "b1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery",
     "query": "SELECT mean(\"Ah_remain\") * mean(\"V\") FROM \"battery\" WHERE (\"topic\" = 'battery/JKBMS1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Ah_remain" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 51.2" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "battery/JKBMS1" }
     ]
    },
    {
     "alias": "b2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery",
     "query": "SELECT mean(\"Ah_remain\") * mean(\"V\") FROM \"battery\" WHERE (\"topic\" = 'battery/JKBMS2') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Ah_remain" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "battery/JKBMS2" }
     ]
    }
   ]
  },
  {
   "title": "SOC",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "b1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "topic" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery",
     "query": "from(bucket: \"local-influxdb\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"battery-system\" and\r\n    r._field == \"state_of_charge\"\r\n  )",
     "select": [
      [
       { "params": [ "SOC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "battery/JKBMS1" }
     ]
    },
    {
     "alias": "b2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "topic" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery",
     "query": "from(bucket: \"local-influxdb\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"battery-system\" and\r\n    r._field == \"state_of_charge\"\r\n  )",
     "select": [
      [
       { "params": [ "SOC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "battery/JKBMS2" }
     ]
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": " ",
     "groupBy": [
      { "params": [ "topic" ], "type": "tag" }
     ],
     "measurement": "battery",
     "query": "from(bucket: \"local-influxdb\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"battery-system\" and\r\n    r._field == \"external_temp\"\r\n  )",
     "select": [
      [
       { "params": [ "Temp1" ], "type": "field" }
      ],
      [
       { "params": [ "Temp2" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cells",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "topic" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "battery",
     "query": "SELECT mean(\"V_01\") AS \"1.01\",mean(\"V_02\") AS \"1.02\",mean(\"V_03\") AS \"1.03\",mean(\"V_04\") AS \"1.04\",mean(\"V_05\") AS \"1.05\",mean(\"V_06\") AS \"1.06\",mean(\"V_07\") AS \"1.07\",mean(\"V_08\") AS \"1.08\",mean(\"V_09\") AS \"1.09\",mean(\"V_10\") AS \"1.10\",mean(\"V_11\") AS \"1.11\",mean(\"V_12\") AS \"1.12\",mean(\"V_13\") AS \"1.13\",mean(\"V_14\") AS \"1.14\",mean(\"V_15\") AS \"1.15\",mean(\"V_16\") AS \"1.16\" FROM \"battery\" WHERE (\"topic\" = 'battery/JKBMS1') AND $timeFilter GROUP BY time($__interval), \"topic\" fill(previous)",
     "select": [
      [
       { "params": [ "V_01" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "battery/JKBMS1" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "topic" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "battery",
     "query": "SELECT mean(\"V_01\") AS \"2.01\",mean(\"V_02\") AS \"2.02\",mean(\"V_03\") AS \"2.03\",mean(\"V_04\") AS \"2.04\",mean(\"V_05\") AS \"2.05\",mean(\"V_06\") AS \"2.06\",mean(\"V_07\") AS \"2.07\",mean(\"V_08\") AS \"2.08\",mean(\"V_09\") AS \"2.09\",mean(\"V_10\") AS \"2.10\",mean(\"V_11\") AS \"2.11\",mean(\"V_12\") AS \"2.12\",mean(\"V_13\") AS \"2.13\",mean(\"V_14\") AS \"2.14\",mean(\"V_15\") AS \"2.15\",mean(\"V_16\") AS \"2.16\" FROM \"battery\" WHERE (\"topic\" = 'battery/JKBMS2') AND $timeFilter GROUP BY time($__interval), \"topic\" fill(previous)",
     "select": [
      [
       { "params": [ "V_01" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SOC",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "alias": "Batt1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "battery",
     "select": [
      [
       { "params": [ "SOC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "battery/JKBMS1" }
     ]
    },
    {
     "alias": "Batt2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "battery",
     "select": [
      [
       { "params": [ "SOC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "battery/JKBMS2" }
     ]
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Batt1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "battery",
     "query": "from(bucket: \"local-influxdb\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"battery-system\" and\n    r._field == \"power\"\n  )",
     "select": [
      [
       { "params": [ "V" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "battery/JKBMS1" }
     ]
    },
    {
     "alias": "Batt2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "battery",
     "select": [
      [
       { "params": [ "V" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "battery/JKBMS2" }
     ]
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "topic" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "battery",
     "query": "SELECT abs(mean(\"Ain\")) AS \"Ain-1\", abs(mean(\"Aout\")) AS \"Aout-1\" FROM \"battery\" WHERE (\"topic\" = 'battery/JKBMS1') AND $timeFilter GROUP BY time($__interval), \"topic\" fill(previous)",
     "select": [
      [
       { "params": [ "Ain" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Ain-1" ], "type": "alias" }
      ],
      [
       { "params": [ "Aout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Aout-1" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "battery/JKBMS1" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "topic" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "battery",
     "query": "SELECT abs(mean(\"Ain\")) AS \"Ain-2\", abs(mean(\"Aout\")) AS \"Aout-2\" FROM \"battery\" WHERE (\"topic\" = 'battery/JKBMS2') AND $timeFilter GROUP BY time($__interval), \"topic\" fill(previous)",
     "select": [
      [
       { "params": [ "Ain" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "Aout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}